[module]
  [module.hugoVersion]
    min = "0.113.0"

[[menu.main]]
identifier = "post"
name = "Posts"
url = "/"
weight = 1
[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/post/"
weight = 2

[taxonomies]
tags = "tags"

[params]
title="B1gCat | Home"
description = "B1gCat|Home"
images = ['images/logo.jpg']
footnote = """
Follow me on <a class=link href=https://github.com/b1gcat target=_blank rel=noopener>GitHub</a>
"""
keywords = ["blog", "b1gcat","reverse","developer"]
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
since = "2023"
toc = false
showWordCount = true
showReadingTime = true
rootFontSize = "120%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = false

[params.buymeacoffee]
code = """
"""
